project:
  type: book
  output-dir: docs

book:
  title: "Apuntes TCT-TRI"
  author: "Arturo Caballero"
  date: last-modified
  date-format: "[Actualizado en] MMMM, YYYY"
  favicon: Gemini_Generated_irt.png
  cover-image: Gemini_Generated_irt.png
  publisher: "Arturo Caballero"
  description: Apuntes de teoría clásica de los test y teoría de respuesta al ítem. 
  keyword: clases, tct, tri, ctt, irt, UNAH, caballero000, mirt, tam, investigacion, research
  
  reader-mode: true
  url: https://caballeroarturo.github.io/cv/
  page-navigation: true
  sharing: [twitter, linkedin]
  sidebar: 
    logo: Gemini_Generated_irt.png
    search: true
  repo-url: https://caballeroarturo.github.io/cv/
  #
  #repo-subdir: book
  #repo-branch: main
  #repo-actions: [edit, issue, source]
  
  downloads: [pdf] #epub
  image: Gemini_Generated_irt.png
  
  page-footer: 
    left: | 
      Notas de <a href="https://caballeroarturo.github.io/cv/">Caballero</a>.
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  
  chapters:
    - index.qmd
    - part: tct.qmd
      chapters: 
        - contenido/TCT01_distractores.qmd
    - part: TRI.qmd
      chapters: 
        - contenido/IRT01_Rasch.qmd
    - apendice.qmd
    - references.qmd
bibliography: references.bib
csl: chicago-author-date-17th-edition.csl
link-citations: true

format:
  html:
    theme:
      dark: superhero
      light: cosmo
    lang: es
    code-fold: true
    code-link: true
    fig-cap-location: top
    tbl-cap-location: top
    css: custom.css
    toc-depth: 3
    number-sections: true
    number-depth: 3
    sharing: [twitter, linkedin]
    smooth-scroll: true
    author-meta: "Arturo Caballero"
  pdf:
    documentclass: scrreprt
    lang: es
    fig-align: center
    fig-cap-location: top
    tbl-cap-location: top
    toc: true
    toc-depth: 3
    toc-title: Contenido
    number-sections: true
    number-depth: 3
    colorlinks: true
    callout-appearance: simple
    callout-icon: true
  #epub:
  #  toc: true
  #  epub-cover-image: Gemini_Generated_irt.png
  #docx: 
  #  toc: true
  #  number-sections: true
  #  highlight-style: github
execute:
  echo: true
  warning: false
  message: false
  error: false
  code-tools: true
editor: visual

